apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleetshard-editor
rules:
  - apiGroups:
      - registry.apicur.io
    resources:
      - fleetshards
      - fleetshards/status
      - fleetshards/finalizers
    verbs:
      - "*"
