apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleetshard-viewer
rules:
  - apiGroups:
      - registry.apicur.io
    resources:
      - fleetshards
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - registry.apicur.io
    resources:
      - fleetshards/status
      - fleetshards/finalizers
    verbs:
      - get
