apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apicurio-registry-fleet-shard-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apicurio-registry-fleet-shard-operator-role
subjects:
  - kind: ServiceAccount
    name: apicurio-registry-fleet-shard-operator
