apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicurio-registry-fleet-shard-operator-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - registry.apicur.io
    resources:
      - fleetshards/status
    verbs:
      - get
      - patch
      - update
