apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-fleet-shard-operator
  labels:
    name: apicurio-registry-fleet-shard-operator
spec:
  selector:
    matchLabels:
      name: apicurio-registry-fleet-shard-operator
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: apicurio-registry-fleet-shard-operator
    spec:
      serviceAccountName: apicurio-registry-fleet-shard-operator
      containers:
        - name: apicurio-registry-fleet-shard-operator
          image: REGISTRY_FLEET_SHARD_OPERATOR_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
