apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/operator.deployment.yaml

images:
  - name: REGISTRY_FLEET_SHARD_OPERATOR_IMAGE
    newName: quay.io/jsenkorh/apicurio-registry-fleet-shard-operator
    newTag: latest-snapshot
